name: Build resumes

on:
  push:
    branches: [ "main", "master"]
  workflow_dispatch: # run manualy from the UI
jobs:
  build-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Dependencies
        run: |
          pip install -r --upgrade pip
          pip install -r requirements.txt
          playwright install chromium --with-deps

      - name: Build the base resume
        env:
          RESUME_EMAIL: ${{ secrets.RESUME_EMAIL}}
          RESUME_PHONE: ${{ secrets.RESUME_PHONE}}
          RESUME_GITHUB: ${{ secrets.RESUME_GITHUB}}
          RESUME_BLOG: ${{ secrets.RESUME_BLOG}}
          RESUME_LINKEDIN: ${{secrets.RESUME_LINKEDIN}}
        run: python3 src/build.py
        

      - name: Build Variant Resumes
        env:
          RESUME_EMAIL: ${{ secrets.RESUME_EMAIL}}
          RESUME_PHONE: ${{ secrets.RESUME_PHONE}}
          RESUME_GITHUB: ${{ secrets.RESUME_GITHUB}}
          RESUME_BLOG: ${{ secrets.RESUME_BLOG}}
          RESUME_LINKEDIN: ${{secrets.RESUME_LINKEDIN}}

        run: |
          if [ -d "variants" ]; then
            for file in variants/*.yaml; do
              echo "Building variants: $file"
              python3 src/build.py "$file"
            done
          fi
      - name: upload PDF as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-resumes
          path: dist/*.pdf
          retention-days: 14
